# Generated by Django 2.0.5 on 2018-07-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180706_0240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
